stages:
  - merge

merge_quangtrung_to_main:
  stage: merge
  image: alpine:latest
  before_script:
    - apk add --no-cache git
  script:
    - git config --global user.email "leqtrungggg3105@gmail.com"
    - git config --global user.name "Le-Quang-Trung"
    - git fetch
    - git checkout main            
    - git pull origin main        
    - git fetch
    - git checkout quangtrung 
    - git pull origin quangtrung 
    - git merge main
    - git fetch
    - git checkout main
    - git merge quangtrung
    - git push https://${CI_GITLAB_USER}:${CI_GITLAB_TOKEN}@${CI_REPOSITORY_URL#https://} main

  only:
    - quangtrung